import './globals.css'
import {Funnel_Sans} from 'next/font/google'

const funnel = Funnel_Sans({
  subsets: ['latin'],
  
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={funnel.className}>
      <body>{children}</body>
    </html>
  )
}
